export enum WeatherActionTypes {
    GET_WEATHER_NOW = '[Weather] GET_WEATHER_NOW',
    GET_WEATHER_NOW_SUCCESS = '[Weather] GET_WEATHER_NOW_SUCCESS',
    GET_WEATHER_NOW_FAIL = '[Weather] GET_WEATHER_NOW_FAIL',

    GET_WEATHER_HOURLY = '[Weather] GET_WEATHER_HOURLY',
    GET_WEATHER_HOURLY_SUCCESS = '[Weather] GET_WEATHER_HOURLY_SUCCESS',
    GET_WEATHER_HOURLY_FAIL = '[Weather] GET_WEATHER_HOURLY_FAIL',

    GET_WEATHER_DAILY = '[Weather] GET_WEATHER_DAILY',
    GET_WEATHER_DAILY_SUCCESS = '[Weather] GET_WEATHER_DAILY_SUCCESS',
    GET_WEATHER_DAILY_FAIL = '[Weather] GET_WEATHER_DAILY_FAIL',

    SEARCH_WEATHER = '[Weather] SEARCH_WEATHER',
    SEARCH_WEATHER_SUCCESS = '[Weather] SEARCH_WEATHER_SUCCESS',
    SEARCH_WEATHER_FAIL = '[Weather] SEARCH_WEATHER_FAIL',

    GET_WEATHER_FAVOURITE = '[Weather] GET_WEATHER_FAVOURITE',
    GET_WEATHER_FAVOURITE_SUCCESS = '[Weather] GET_WEATHER_FAVOURITE_SUCCESS',
    GET_WEATHER_FAVOURITE_FAIL = '[Weather] GET_WEATHER_FAVOURITE_FAIL',

    ADD_WEATHER = '[Weather] ADD_WEATHER',
    ADD_WEATHER_SUCCESS = '[Weather] ADD_WEATHER_SUCCESS',
    ADD_WEATHER_FAIL = '[Weather] ADD_WEATHER_FAIL',

    REMOVE_WEATHER = '[Weather] REMOVE_WEATHER',
    REMOVE_WEATHER_SUCCESS = '[Weather] REMOVE_WEATHER_SUCCESS',
    REMOVE_WEATHER_FAIL = '[Weather] REMOVE_WEATHER_FAIL',
}